"""change column type

Revision ID: 1a746142d210
Revises: 964778967caf
Create Date: 2025-11-02 09:50:21.821902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a746142d210'
down_revision = '964778967caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.BLOB(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.Text(),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
