"""update file and key table

Revision ID: 3b469c84e1c9
Revises: 57ea833d857c
Create Date: 2025-10-27 17:37:19.149046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b469c84e1c9'
down_revision = '57ea833d857c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('recipient', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('aes_key', sa.Text(), nullable=True))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('key_data')
        batch_op.alter_column('private_key',new_column_name='rsa_private_key')
        batch_op.alter_column('public_key', new_column_name='rsa_public_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('private_key', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('public_key', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('key_data', sa.TEXT(), nullable=True))
        batch_op.create_foreign_key(None, 'files', ['file_id'], ['id'])
        batch_op.drop_column('rsa_private_key')
        batch_op.drop_column('rsa_public_key')
        batch_op.drop_column('aes_key')
        batch_op.drop_column('recipient')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
