"""fix file id foreign key

Revision ID: 548d4b90a990
Revises: c0b55b467df0
Create Date: 2025-09-06 21:33:16.021294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548d4b90a990'
down_revision = 'c0b55b467df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('original_url', sa.Text(), nullable=True),
    sa.Column('encrypted_url', sa.Text(), nullable=True),
    sa.Column('decrypted_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('key_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keys')
    op.drop_table('files')
    # ### end Alembic commands ###
