"""Add some column into file and key table

Revision ID: 57ea833d857c
Revises: 1efce00a7109
Create Date: 2025-10-25 21:39:39.714636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57ea833d857c'
down_revision = '1efce00a7109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('key_filename', sa.String(length=100), nullable=True))

    with op.batch_alter_table('keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private_key', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('public_key', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keys', schema=None) as batch_op:
        batch_op.drop_column('public_key')
        batch_op.drop_column('private_key')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('key_filename')
        batch_op.drop_column('recipient')

    # ### end Alembic commands ###
