"""update file data column

Revision ID: 753e5a5ae858
Revises: 1a746142d210
Create Date: 2025-11-02 19:12:48.894531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753e5a5ae858'
down_revision = '1a746142d210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.TEXT(),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.LargeBinary(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
