"""Add the encrypted_b64 col into file model

Revision ID: 796757836cb5
Revises: 753e5a5ae858
Create Date: 2025-11-02 20:51:55.811717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796757836cb5'
down_revision = '753e5a5ae858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_b64', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('encrypted_b64')

    # ### end Alembic commands ###
