"""add some column to File table

Revision ID: 8f0c503d6659
Revises: 548d4b90a990
Create Date: 2025-09-07 12:45:09.654666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f0c503d6659'
down_revision = '548d4b90a990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=False, server_default="temp"))
        batch_op.add_column(sa.Column('mimetype', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('data', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('data')
        batch_op.drop_column('mimetype')
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
