"""add the MetaData table

Revision ID: 964778967caf
Revises: ea99bfbbf8b1
Create Date: 2025-10-30 21:04:18.733152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964778967caf'
down_revision = 'ea99bfbbf8b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metaData',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=100), nullable=True),
    sa.Column('encrypted_filename', sa.String(length=100), nullable=True),
    sa.Column('recipient_name', sa.String(length=100), nullable=True),
    sa.Column('rcpt_pubkey_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metaData')
    # ### end Alembic commands ###
