"""add the mimetype col

Revision ID: c4edc08a5d65
Revises: 796757836cb5
Create Date: 2025-11-03 09:16:20.647275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4edc08a5d65'
down_revision = '796757836cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mimetype', sa.String(length=100), nullable=True))
        batch_op.alter_column('profile_pic',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.LargeBinary(),
               existing_nullable=True)
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=80), nullable=True))
        batch_op.alter_column('profile_pic',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.drop_column('mimetype')

    # ### end Alembic commands ###
