"""Remove url columns from file

Revision ID: c868ae361af7
Revises: 8f0c503d6659
Create Date: 2025-10-03 22:30:22.768675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c868ae361af7'
down_revision = '8f0c503d6659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('original_url')
        batch_op.drop_column('encrypted_url')
        batch_op.drop_column('decrypted_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decrypted_url', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('encrypted_url', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('original_url', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
