"""update file table

Revision ID: ea99bfbbf8b1
Revises: 3b469c84e1c9
Create Date: 2025-10-29 16:25:32.136697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea99bfbbf8b1'
down_revision = '3b469c84e1c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keys', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('file_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'files', ['file_id'], ['id'])

    # ### end Alembic commands ###
